package view;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
//Incompatáivel com java 7
//import java.time.LocalDateTime;
//import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import controller.*;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Position;

public class InterfaceChaves extends javax.swing.JFrame {

    public InterfaceChaves() {
        initComponents();
        Calendar cal = GregorianCalendar.getInstance();
        TimeZone tz = TimeZone.getTimeZone("America/Recife");
	TimeZone.setDefault(tz);
        cal.setTimeZone(tz);
        i3.setText(Integer.toString(cal.get(Calendar.YEAR)));
        f3.setText(Integer.toString(cal.get(Calendar.YEAR)));
        jLabel16.setText("Anteriores a "+ Integer.toString(cal.get(Calendar.YEAR)-1));
        jLabel17.setText("Sem empréstimos em "+ Integer.toString(cal.get(Calendar.YEAR)-1) + " e "+ Integer.toString(cal.get(Calendar.YEAR)));
        
        //Incompatível com java 7
        //LocalDateTime dia = LocalDateTime.now();
        //i3.setText(Integer.toString(dia.getYear()));
        //f3.setText(Integer.toString(dia.getYear()));          
        //jLabel16.setText("Anteriores a "+ Integer.toString(dia.getYear()-1));
        //jLabel17.setText("Sem empréstimos em "+ Integer.toString(dia.getYear()-1) + " e "+ Integer.toString(dia.getYear()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        relatorios = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        telaemprestimo = new javax.swing.JPanel();
        pEmprestimo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chave = new javax.swing.JTextField();
        btemprestar = new javax.swing.JButton();
        nome = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        pDevolucao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadevol = new javax.swing.JList<>();
        btdevolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        telainserir = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cadmatricula = new javax.swing.JTextField();
        cadnome = new javax.swing.JTextField();
        btcadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btcadastrar_objeto = new javax.swing.JButton();
        btalterar_usuario1 = new javax.swing.JButton();
        telarelatorio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelRelatorio = new javax.swing.JLabel();
        relatorioEmprestimo = new javax.swing.JButton();
        relatorioMesAnterior = new javax.swing.JButton();
        relatorioMesAtual = new javax.swing.JButton();
        cbmeses = new javax.swing.JComboBox<>();
        relatorioMes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        i1 = new javax.swing.JFormattedTextField();
        i2 = new javax.swing.JFormattedTextField();
        i3 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        f1 = new javax.swing.JFormattedTextField();
        f2 = new javax.swing.JFormattedTextField();
        f3 = new javax.swing.JFormattedTextField();
        relatorioPeriodo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btRelatorioUsuarios = new javax.swing.JButton();
        telaadministracao = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        alterarusuario_matricula = new javax.swing.JTextField();
        alterarusuario_nome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_alterar = new javax.swing.JTable();
        btalterar_buscar = new javax.swing.JButton();
        btalterar_usuario = new javax.swing.JButton();
        semUsuarioBusca = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cabecalho = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        sistemachaves = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(190, 210, 240));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(90, 100, 150));
        jTabbedPane1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        telaemprestimo.setBackground(new java.awt.Color(255, 255, 255));
        telaemprestimo.setMaximumSize(new java.awt.Dimension(1200, 1200));

        pEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        pEmprestimo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pEmprestimo.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Matrícula");

        matricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                matriculaFocusGained(evt);
            }
        });
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+1f));
        jLabel2.setText("Chave");

        chave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chaveFocusGained(evt);
            }
        });
        chave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaveActionPerformed(evt);
            }
        });

        btemprestar.setText("Emprestar");
        btemprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btemprestarActionPerformed(evt);
            }
        });

        nome.setFont(nome.getFont().deriveFont(nome.getFont().getSize()+2f));
        nome.setForeground(new java.awt.Color(90, 100, 150));
        nome.setName(""); // NOI18N

        data.setFont(data.getFont().deriveFont(data.getFont().getSize()+2f));
        data.setForeground(new java.awt.Color(90, 100, 150));

        javax.swing.GroupLayout pEmprestimoLayout = new javax.swing.GroupLayout(pEmprestimo);
        pEmprestimo.setLayout(pEmprestimoLayout);
        pEmprestimoLayout.setHorizontalGroup(
            pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEmprestimoLayout.createSequentialGroup()
                        .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEmprestimoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE))
                            .addGroup(pEmprestimoLayout.createSequentialGroup()
                                .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(29, 29, 29)))
                        .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btemprestar)
                            .addComponent(chave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        pEmprestimoLayout.setVerticalGroup(
            pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(chave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btemprestar)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDevolucao.setBackground(new java.awt.Color(255, 255, 255));
        pDevolucao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBorder(null);

        listadevol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listadevol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listadevol.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listadevol.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listadevolValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listadevol);

        javax.swing.GroupLayout pDevolucaoLayout = new javax.swing.GroupLayout(pDevolucao);
        pDevolucao.setLayout(pDevolucaoLayout);
        pDevolucaoLayout.setHorizontalGroup(
            pDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDevolucaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pDevolucaoLayout.setVerticalGroup(
            pDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        btdevolver.setText("Devolver");
        btdevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdevolverActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(90, 100, 150));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Empréstimo");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout telaemprestimoLayout = new javax.swing.GroupLayout(telaemprestimo);
        telaemprestimo.setLayout(telaemprestimoLayout);
        telaemprestimoLayout.setHorizontalGroup(
            telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaemprestimoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pDevolucao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        telaemprestimoLayout.setVerticalGroup(
            telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaemprestimoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaemprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(telaemprestimoLayout.createSequentialGroup()
                        .addComponent(pDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btdevolver)))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("   Empréstimo e Devolução   ", telaemprestimo);

        telainserir.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(262, 120));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+1f));
        jLabel5.setText("Matrícula");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+1f));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nome");

        cadmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadmatriculaActionPerformed(evt);
            }
        });

        cadnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadnomeActionPerformed(evt);
            }
        });

        btcadastrar.setText("Cadastrar");
        btcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btcadastrar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadmatricula)
                            .addComponent(cadnome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cadmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cadnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btcadastrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(90, 100, 150));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cadastro de Usuário");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(83, 17));

        jLabel18.setBackground(new java.awt.Color(90, 100, 150));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Objetos");
        jLabel18.setMaximumSize(new java.awt.Dimension(158, 17));
        jLabel18.setMinimumSize(new java.awt.Dimension(158, 17));
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(83, 17));

        btcadastrar_objeto.setText("Cadastrar Objeto");
        btcadastrar_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrar_objetoActionPerformed(evt);
            }
        });

        btalterar_usuario1.setText("Alterar Objeto");
        btalterar_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterar_usuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telainserirLayout = new javax.swing.GroupLayout(telainserir);
        telainserir.setLayout(telainserirLayout);
        telainserirLayout.setHorizontalGroup(
            telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telainserirLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123)
                .addGroup(telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telainserirLayout.createSequentialGroup()
                        .addComponent(btcadastrar_objeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btalterar_usuario1)))
                .addContainerGap())
        );
        telainserirLayout.setVerticalGroup(
            telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telainserirLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telainserirLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btcadastrar_objeto)
                            .addComponent(btalterar_usuario1)))
                    .addGroup(telainserirLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Cadastros    ", telainserir);

        telarelatorio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelRelatorio.setBackground(new java.awt.Color(90, 100, 150));
        labelRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        labelRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelatorio.setText("Relatórios");
        labelRelatorio.setOpaque(true);

        relatorioEmprestimo.setText("Empréstimos ativos");
        relatorioEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioEmprestimoActionPerformed(evt);
            }
        });

        relatorioMesAnterior.setText("Mês anterior");
        relatorioMesAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioMesAnteriorActionPerformed(evt);
            }
        });

        relatorioMesAtual.setText("Mês atual");
        relatorioMesAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioMesAtualActionPerformed(evt);
            }
        });

        cbmeses.setFont(cbmeses.getFont().deriveFont(cbmeses.getFont().getStyle() | java.awt.Font.BOLD, cbmeses.getFont().getSize()+1));
        cbmeses.setForeground(new java.awt.Color(90, 100, 150));
        cbmeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cbmeses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbmesesKeyPressed(evt);
            }
        });

        relatorioMes.setText("Relatório por mês");
        relatorioMes.setMaximumSize(new java.awt.Dimension(93, 23));
        relatorioMes.setMinimumSize(new java.awt.Dimension(93, 23));
        relatorioMes.setPreferredSize(new java.awt.Dimension(93, 23));
        relatorioMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioMesActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()+1f));
        jLabel8.setText("Período inicial:");

        i1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd"))));
        i1.setFont(i1.getFont().deriveFont(i1.getFont().getSize()+1f));
        i1.setNextFocusableComponent(i2);
        i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1ActionPerformed(evt);
            }
        });

        i2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM"))));
        i2.setFont(i2.getFont().deriveFont(i2.getFont().getSize()+1f));
        i2.setNextFocusableComponent(i3);
        i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2ActionPerformed(evt);
            }
        });

        i3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        i3.setFont(i3.getFont().deriveFont(i3.getFont().getSize()+1f));
        i3.setNextFocusableComponent(f1);

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getSize()+1f));
        jLabel9.setText("Período final:");

        f1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd"))));
        f1.setFont(f1.getFont().deriveFont(f1.getFont().getSize()+1f));
        f1.setNextFocusableComponent(f2);
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        f2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM"))));
        f2.setFont(f2.getFont().deriveFont(f2.getFont().getSize()+1f));
        f2.setNextFocusableComponent(f3);
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        f3.setFont(f3.getFont().deriveFont(f3.getFont().getSize()+1f));

        relatorioPeriodo.setText("Relatório por período");
        relatorioPeriodo.setMaximumSize(new java.awt.Dimension(93, 23));
        relatorioPeriodo.setMinimumSize(new java.awt.Dimension(93, 23));
        relatorioPeriodo.setPreferredSize(new java.awt.Dimension(93, 23));
        relatorioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioPeriodoActionPerformed(evt);
            }
        });

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getSize()+1f));
        jLabel10.setText("/");

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getSize()+1f));
        jLabel11.setText("/");

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getSize()+1f));
        jLabel12.setText("/");

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getSize()+1f));
        jLabel13.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(relatorioPeriodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i3)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(relatorioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btRelatorioUsuarios.setText("Relatório de usuários");
        btRelatorioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(relatorioMesAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(relatorioEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                            .addComponent(relatorioMesAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbmeses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(relatorioMes, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(btRelatorioUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(relatorioEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmeses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatorioMesAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relatorioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(relatorioMesAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btRelatorioUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telarelatorioLayout = new javax.swing.GroupLayout(telarelatorio);
        telarelatorio.setLayout(telarelatorioLayout);
        telarelatorioLayout.setHorizontalGroup(
            telarelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telarelatorioLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        telarelatorioLayout.setVerticalGroup(
            telarelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telarelatorioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   Relatórios   ", telarelatorio);

        telaadministracao.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(jLabel14.getFont().deriveFont(jLabel14.getFont().getSize()+1f));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Buscar pela matrícula:");

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getSize()+1f));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("OU Buscar pelo nome:");

        alterarusuario_matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alterarusuario_matriculaKeyPressed(evt);
            }
        });

        alterarusuario_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alterarusuario_nomeKeyPressed(evt);
            }
        });

        tabela_alterar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_alterarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_alterar);

        btalterar_buscar.setText("Buscar");
        btalterar_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterar_buscarActionPerformed(evt);
            }
        });

        btalterar_usuario.setText("Alterar");
        btalterar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterar_usuarioActionPerformed(evt);
            }
        });

        semUsuarioBusca.setForeground(new java.awt.Color(255, 0, 51));

        jLabel19.setBackground(new java.awt.Color(90, 100, 150));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Alterar usuário");
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(83, 17));

        jLabel4.setText("Selecione o usuário que deseja alterar:");

        jButton2.setText("Apagar empréstimos antigos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Apagar usuários antigos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Anteriores a");

        jLabel17.setText("Sem empréstimos em");

        javax.swing.GroupLayout telaadministracaoLayout = new javax.swing.GroupLayout(telaadministracao);
        telaadministracao.setLayout(telaadministracaoLayout);
        telaadministracaoLayout.setHorizontalGroup(
            telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaadministracaoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaadministracaoLayout.createSequentialGroup()
                        .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(semUsuarioBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaadministracaoLayout.createSequentialGroup()
                        .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaadministracaoLayout.createSequentialGroup()
                                .addComponent(btalterar_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btalterar_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alterarusuario_nome)
                            .addComponent(alterarusuario_matricula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(telaadministracaoLayout.createSequentialGroup()
                                .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        telaadministracaoLayout.setVerticalGroup(
            telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaadministracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaadministracaoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaadministracaoLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarusuario_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarusuario_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btalterar_usuario)
                            .addComponent(btalterar_buscar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semUsuarioBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaadministracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("   Administração   ", telaadministracao);

        cabecalho.setBackground(new java.awt.Color(255, 255, 255));

        logo.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        logo.setForeground(new java.awt.Color(153, 0, 0));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N

        sistemachaves.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        sistemachaves.setForeground(new java.awt.Color(153, 0, 0));
        sistemachaves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sistemachaves.setText("Sistema de chaves");

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sistemachaves)
                .addGap(17, 17, 17))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sistemachaves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("  Empréstimo e Devolução  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencherLista();

    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

    }//GEN-LAST:event_formWindowLostFocus

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        if(jTabbedPane1.getSelectedIndex() == 0){
            matricula.requestFocus();           
            btemprestar.setEnabled(false);   
        }
        if (jTabbedPane1.getSelectedIndex() == 1){
            cadmatricula.requestFocus();
        }
        
        btalterar_usuario.setEnabled(false);
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void relatorioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioPeriodoActionPerformed
        pegarPeriodo();
    }//GEN-LAST:event_relatorioPeriodoActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        relatorioPeriodo.requestFocus();
    }//GEN-LAST:event_f2ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        f2.requestFocus();
    }//GEN-LAST:event_f1ActionPerformed

    private void i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2ActionPerformed
        f1.requestFocus();
    }//GEN-LAST:event_i2ActionPerformed

    private void i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1ActionPerformed
        i2.requestFocus();
    }//GEN-LAST:event_i1ActionPerformed

    private void relatorioMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioMesActionPerformed
        RelatorioMes rel = new RelatorioMes();
        rel.setVisible(true);
        String nomemes = (String)cbmeses.getSelectedItem();
        int nummes = (cbmeses.getSelectedIndex())+1;
        rel.relatorioMes(nummes, nomemes);
    }//GEN-LAST:event_relatorioMesActionPerformed

    private void cbmesesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbmesesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        relatorioMes.requestFocus();
    }//GEN-LAST:event_cbmesesKeyPressed

    private void relatorioMesAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioMesAtualActionPerformed
        RelatorioMes rel = new RelatorioMes();
        rel.setVisible(true);
        rel.relatorioMesAtual();
    }//GEN-LAST:event_relatorioMesAtualActionPerformed

    private void relatorioMesAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioMesAnteriorActionPerformed
        RelatorioMes rel = new RelatorioMes();
        rel.setVisible(true);
        rel.relatorioMesAnterior();
    }//GEN-LAST:event_relatorioMesAnteriorActionPerformed

    private void relatorioEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioEmprestimoActionPerformed
        RelatorioEmpAtivo rel = new RelatorioEmpAtivo();
        rel.setVisible(true);
    }//GEN-LAST:event_relatorioEmprestimoActionPerformed

    private void btcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarActionPerformed
        cadastrarUsuario();
    }//GEN-LAST:event_btcadastrarActionPerformed

    private void cadnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadnomeActionPerformed
        cadastrarUsuario();
    }//GEN-LAST:event_cadnomeActionPerformed

    private void cadmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadmatriculaActionPerformed
        cadnome.requestFocus();
    }//GEN-LAST:event_cadmatriculaActionPerformed

    private void btdevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdevolverActionPerformed
        devolver();
    }//GEN-LAST:event_btdevolverActionPerformed

    private void listadevolValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listadevolValueChanged
        if(listadevol.getSelectedValue()!=null){
            btdevolver.requestFocus(); 
        }

    }//GEN-LAST:event_listadevolValueChanged

    private void btemprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btemprestarActionPerformed
        emprestar();
    }//GEN-LAST:event_btemprestarActionPerformed

    private void chaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaveActionPerformed
        emprestar();
    }//GEN-LAST:event_chaveActionPerformed

    private void chaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chaveFocusGained
        exibirEmpUsuario();
    }//GEN-LAST:event_chaveFocusGained

    private void matriculaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_matriculaFocusGained
        //limpar();
    }//GEN-LAST:event_matriculaFocusGained

    private void btRelatorioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioUsuariosActionPerformed
       
        try {
            
            ArrayList lista = new UsuarioController().relatorioUsuarios();                       
            String path = System.getProperty("user.home") + "/Desktop/relatorio_Temporario_Usuario.txt";
            BufferedWriter buffWrite = new BufferedWriter(new FileWriter(path));
            
            for (int i = 0; i < lista.size(); i++){
                String matricula = (String)lista.get(i);
                String nome = (String)lista.get(i+1);
                while(matricula.length()< 20){
                    matricula = matricula+" ";
                }
                buffWrite.append(matricula);
                buffWrite.append("\t");
                buffWrite.append(nome);
                buffWrite.newLine();
                i++;  
            }

            buffWrite.close();
            File relatorio = new File(path);
            Desktop.getDesktop().open(relatorio);
            
        } catch (IOException | SQLException ex) {
            Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRelatorioUsuariosActionPerformed

    private void btalterar_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterar_usuario1ActionPerformed
        alterarObjeto();
    }//GEN-LAST:event_btalterar_usuario1ActionPerformed

    private void btcadastrar_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrar_objetoActionPerformed
        cadastrarObjeto();
    }//GEN-LAST:event_btcadastrar_objetoActionPerformed

    private void btalterar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterar_usuarioActionPerformed
        alterarUsuario();
    }//GEN-LAST:event_btalterar_usuarioActionPerformed

    private void btalterar_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterar_buscarActionPerformed
        buscarAlterarUsuario();
    }//GEN-LAST:event_btalterar_buscarActionPerformed

    private void tabela_alterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_alterarMouseClicked

        int row = tabela_alterar.getSelectedRow();
        String inome = tabela_alterar.getModel().getValueAt(row, 1).toString();
        String imatricula = tabela_alterar.getModel().getValueAt(row, 0).toString();

        alterarusuario_matricula.setText(imatricula);
        alterarusuario_nome.setText(inome);
    }//GEN-LAST:event_tabela_alterarMouseClicked

    private void alterarusuario_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alterarusuario_nomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        buscarAlterarUsuario();
    }//GEN-LAST:event_alterarusuario_nomeKeyPressed

    private void alterarusuario_matriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alterarusuario_matriculaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        buscarAlterarUsuario();
    }//GEN-LAST:event_alterarusuario_matriculaKeyPressed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        
        if( matricula.getText().trim().length()<=3 && matricula.getText().trim().length()>0 && listadevol.getModel().getSize()!=0){
            int index = listadevol.getNextMatch(matricula.getText(),0,Position.Bias.Forward);
            if(index != -1){
                listadevol.setSelectedIndex(index);
            }            
        } else if(matricula.getText().trim().length()>3){
            chave.requestFocus();
        }

    }//GEN-LAST:event_matriculaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,
            "Apagar empréstimos antigos?", "Sim ou não?", JOptionPane.YES_NO_OPTION);
        if(opcao == 0){
            try {
                new EmprestimoController().apagarAntigos();
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
            }          
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,
            "Apagar usuários antigos?", "Sim ou não?", JOptionPane.YES_NO_OPTION);
        if(opcao == 0){
            try {
                new UsuarioController().apagarAntigos();
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }        

    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceChaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alterarusuario_matricula;
    private javax.swing.JTextField alterarusuario_nome;
    private javax.swing.JButton btRelatorioUsuarios;
    private javax.swing.JButton btalterar_buscar;
    private javax.swing.JButton btalterar_usuario;
    private javax.swing.JButton btalterar_usuario1;
    private javax.swing.JButton btcadastrar;
    private javax.swing.JButton btcadastrar_objeto;
    private javax.swing.JButton btdevolver;
    private javax.swing.JButton btemprestar;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JTextField cadmatricula;
    private javax.swing.JTextField cadnome;
    private javax.swing.JComboBox<String> cbmeses;
    private javax.swing.JTextField chave;
    private javax.swing.JLabel data;
    private javax.swing.JFormattedTextField f1;
    private javax.swing.JFormattedTextField f2;
    private javax.swing.JFormattedTextField f3;
    private javax.swing.JFormattedTextField i1;
    private javax.swing.JFormattedTextField i2;
    private javax.swing.JFormattedTextField i3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelRelatorio;
    private javax.swing.JList<String> listadevol;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField matricula;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel pDevolucao;
    private javax.swing.JPanel pEmprestimo;
    private javax.swing.JButton relatorioEmprestimo;
    private javax.swing.JButton relatorioMes;
    private javax.swing.JButton relatorioMesAnterior;
    private javax.swing.JButton relatorioMesAtual;
    private javax.swing.JButton relatorioPeriodo;
    private javax.swing.ButtonGroup relatorios;
    private javax.swing.JLabel semUsuarioBusca;
    private javax.swing.JLabel sistemachaves;
    private javax.swing.JTable tabela_alterar;
    private javax.swing.JPanel telaadministracao;
    private javax.swing.JPanel telaemprestimo;
    private javax.swing.JPanel telainserir;
    private javax.swing.JPanel telarelatorio;
    // End of variables declaration//GEN-END:variables

    
    private void limpar(){
        matricula.setText("");
        chave.setText("");
        nome.setText("");
        data.setText("");
        cadmatricula.setText("");
        cadnome.setText("");
        listadevol.clearSelection();
        
    }
    
    private void cadastrarObjeto(){

        try{

            ArrayList tipos = new ObjetoController().tiposObj();
            String texto = "";

            for(int i = 0; i < tipos.size(); i++){
                texto = texto + tipos.get(i) + "\n";
            }

            String descricao = JOptionPane.showInputDialog("Informe o tipo de objeto\n\nTipos atuais:\n"+texto);

            if(descricao == null || descricao.trim().isEmpty()){
                return;       
            }

            ObjetoController dados = new ObjetoController();
            String id = dados.salvar(descricao);
            JOptionPane.showMessageDialog(null, "Objeto cadastrado com sucesso com o número "+ id);

        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Falha no cadastro"  + e.getLocalizedMessage());

        }  catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Dados com formato inválido!n " + e.getLocalizedMessage());
        }
    }
    
    private void alterarObjeto(){
        String old_id = JOptionPane.showInputDialog("Informe o número do objeto\n");
        
        if(old_id == null ||old_id.trim().isEmpty()){
            return;       
        }
        
        String new_id = JOptionPane.showInputDialog("Informe o novo número do objeto\n");
        
        if(new_id == null ||new_id.trim().isEmpty()){
            return;       
        }
  
        try {
            ArrayList tipos = new ObjetoController().tiposObj();
            String texto = "";

            for(int i = 0; i < tipos.size(); i++){
                texto = texto + tipos.get(i) + "\n";
            }

            String tipo = JOptionPane.showInputDialog("Informe o novo tipo\n\nTipos atuais:\n"+texto);

            if(tipo == null ||tipo.trim().isEmpty()){
                return;       
            }

            ObjetoController obj = new ObjetoController();
            
            obj.alterar(old_id, new_id, tipo);
            JOptionPane.showMessageDialog(null, "Informações alteradas com sucesso.");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar objeto." + ex.getLocalizedMessage());  
            Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
    }
    
    private void alterarUsuario(){
        if(alterarusuario_matricula.getText().trim().isEmpty() || alterarusuario_nome.getText().trim().isEmpty()){
            return;
        }
        if (tabela_alterar.getSelectedRow() == -1){
            buscarAlterarUsuario();
            return;
        }
        
        int row = tabela_alterar.getSelectedRow();
        String old_matricula = tabela_alterar.getModel().getValueAt(row, 0).toString();
        
        String new_matricula = alterarusuario_matricula.getText().trim();
        String new_nome = alterarusuario_nome.getText().trim();
        
        UsuarioController dados = new UsuarioController();
        try {
            dados.alterar(old_matricula, new_matricula, new_nome);
            JOptionPane.showMessageDialog(null, "Informações alteradas com sucesso.");
            btalterar_usuario.setEnabled(false);
            alterarusuario_matricula.setText("");
            alterarusuario_nome.setText("");
            
            DefaultTableModel modelo = (DefaultTableModel)tabela_alterar.getModel();   
        
            if (modelo.getRowCount() > 0){
                for (int i=0; i<modelo.getRowCount(); ){
                    modelo.removeRow(i);
                }            
            }        
            tabela_alterar.setModel(modelo);
            jLabel14.setText("Buscar pela matrícula:");
            jLabel15.setText("OU Buscar pelo nome:");
            jLabel14.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println("Erro GenericDao userListByName"+ ex.getLocalizedMessage());
            btalterar_usuario.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
            btalterar_usuario.setEnabled(false);
        }
       
    }
    
    private void buscarAlterarUsuario(){
        
        if(alterarusuario_matricula.getText().trim().isEmpty() && alterarusuario_nome.getText().trim().isEmpty()){
            return;
        }
        
        semUsuarioBusca.setText("");
        jLabel14.setText("Informe a matrícula correta");
        jLabel15.setText("Informe o nome correto");
        
        DefaultTableModel modelo = (DefaultTableModel)tabela_alterar.getModel();   
        
        if (modelo.getRowCount() > 0){
            for (int i=0; i<modelo.getRowCount(); ){
                modelo.removeRow(i);
            }            
        }        
        tabela_alterar.setModel(modelo);
        tabela_alterar.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabela_alterar.getColumnModel().getColumn(1).setPreferredWidth(400);
        
        //Se buscar pela matrícula. É pra vir só um usuário
        if(alterarusuario_nome.getText().trim().isEmpty()){
            try {
                ArrayList usuario = new UsuarioController().pegarUsuarioMatricula(alterarusuario_matricula.getText());
                
                if (usuario.isEmpty()){
                    semUsuarioBusca.setText("Não encontrado usário com essas informações");
                    btalterar_usuario.setEnabled(false);
                    jLabel14.setText("Buscar pela matrícula:");
                    jLabel15.setText("OU Buscar pelo nome:");
                    jLabel4.setText("");
                    return;                    
                }

                modelo.addRow(new Object[]{null,null,null,null});
                modelo.setValueAt(usuario.get(0), 0, 0); //valor, linha, coluna
                modelo.setValueAt(usuario.get(1), 0, 1);
                alterarusuario_matricula.setText(String.valueOf(usuario.get(0)));
                alterarusuario_nome.setText(String.valueOf(usuario.get(1)));
                tabela_alterar.setRowSelectionInterval(0, 0);
                btalterar_usuario.setEnabled(true);
                               
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
                jLabel14.setText("Buscar pela matrícula:");
                jLabel15.setText("OU Buscar pelo nome:");
                jLabel4.setText("");
            }
 
        } else{
            ArrayList<String> listaUsuarios = new ArrayList<String>();

            try {
                listaUsuarios = new UsuarioController().pegarUsuariosNome(alterarusuario_nome.getText());
                
                if (listaUsuarios.isEmpty()){
                    semUsuarioBusca.setText("Não encontrado usário com essas informações");
                    btalterar_usuario.setEnabled(false);
                    jLabel14.setText("Buscar pela matrícula:");
                    jLabel15.setText("OU Buscar pelo nome:");
                    jLabel4.setText("");
                    return;                    
                }
                btalterar_usuario.setEnabled(true);
                
                int row = 0;

                alterarusuario_matricula.setText(listaUsuarios.get(0));
                alterarusuario_nome.setText(listaUsuarios.get(1));
                
                for(int i = 0; i < listaUsuarios.size(); i+=2){
                    modelo.addRow(new Object[]{null,null,null,null});
                    modelo.setValueAt(listaUsuarios.get(i),row, 0);
                    modelo.setValueAt(listaUsuarios.get(i+1), row, 1);
                    row++;  
                }
                tabela_alterar.setRowSelectionInterval(0,0);
   
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceChaves.class.getName()).log(Level.SEVERE, null, ex);
                jLabel14.setText("Buscar pela matrícula:");
                jLabel15.setText("OU Buscar pelo nome:");
                jLabel4.setText("");
            }
            
        }
        
    }
       
    private void cadastrarUsuario(){
                  
        if(cadmatricula.getText().trim().isEmpty() || cadnome.getText().trim().isEmpty()){
            return;
        }

        try{
            UsuarioController dados = new UsuarioController();
            dados.salvar(cadmatricula.getText(), cadnome.getText());
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso.");
            String aux = cadmatricula.getText();
            jTabbedPane1.setSelectedIndex(0);                                   
            limpar();
            copy(aux);
            matricula.setText(aux);
            chave.requestFocus();

        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Falha no cadastro" + e.getLocalizedMessage());

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Dados com formato inválido!n" + e.getLocalizedMessage());
        }

    }
    
    private void copy(String aux){
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(aux);
        clipboard.setContents(selection, null);
    }
     
    private void emprestar() {

        if(nome.getText().trim().isEmpty() || chave.getText().trim().isEmpty()){
            return;
        }
        
        try{        
            EmprestimoController dados = new EmprestimoController();
            String msg = dados.salvar(matricula.getText(), chave.getText());
            
            if (!msg.isEmpty()){
                JOptionPane.showMessageDialog(this, msg);                
            }
            
            preencherLista();
            limpar();
            matricula.requestFocus();
        
        } catch (ParseException | SQLException e) { 
            //System.out.println("ERRO: Interface" + e.getLocalizedMessage());
            String aux = matricula.getText();
            limpar();
            jTabbedPane1.setSelectedIndex(1);
            cadmatricula.setText(aux);           
        }

    }

    private void exibirEmpUsuario() {
        if (matricula.getText().trim().isEmpty())
            return; 
 
        try{            
            ArrayList infoEmprestimo = new EmprestimoController().exibirEmpUsuario(matricula.getText());

            if(!infoEmprestimo.isEmpty()){
                nome.setForeground(new Color(90,100,150));
                nome.setText("Nome: "+infoEmprestimo.get(1));  
                Calendar cal = GregorianCalendar.getInstance();
                
                TimeZone tz = TimeZone.getTimeZone("America/Recife");
		TimeZone.setDefault(tz);
                cal.setTimeZone(tz);
                
                String dataatual = dataMenor10(cal.get(Calendar.DATE)) +
                        "/"+
                        dataMenor10(cal.get(Calendar.MONTH)+1)+
                        "/"+
                        Integer.toString(cal.get(Calendar.YEAR))+
                        " - "+
                        dataMenor10(cal.get(Calendar.HOUR_OF_DAY))+
                        ":"+
                        dataMenor10(cal.get(Calendar.MINUTE));
                
                data.setText("Data de empréstimo: " + dataatual);
                //Incompatível com java 7
                //LocalDateTime dia = LocalDateTime.now();
                //DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy - HH:mm");
                //data.setText("Data de empréstimo: " + dia.format(formatador));
                btemprestar.setEnabled(true);
                        
            }else{
                nome.setText("Usuário não cadastrado");
                nome.setForeground(new Color(153,0,0));
                cadmatricula.setText(matricula.getText());
                matricula.requestFocus();
                data.setText("");
                btemprestar.setEnabled(false);               
            }
                    
        } catch(SQLException e){
            //System.out.println("ERRO: Interface" + e.getLocalizedMessage());
            nome.setText("Usuário não cadastrado");
            nome.setForeground(new Color(153,0,0));
            cadmatricula.setText(matricula.getText());
            data.setText("");
            btemprestar.setEnabled(false);
        }
                  
    }
    
    private String dataMenor10(int data){
        //String addZero; = (data < 10) ?  "0"+Integer.toString(data): Integer.toString(data);
        String addZero = Integer.toString(data);
        if(data < 10){
            addZero = "0"+Integer.toString(data);           
        }
        return addZero;
    }

    private void preencherLista() {        
        DefaultListModel model = new DefaultListModel();
        listadevol.setModel(model);

        ArrayList<String> listaemprestimo = new ArrayList<String>();
        try {
            listaemprestimo = new EmprestimoController().listarAtivos();
            
            for(Object lista : listaemprestimo){
                model.addElement(lista);               
            }   
        
        } catch (SQLException e) {
            Logger.getLogger("Erro Interface " + e.getLocalizedMessage());
            
        }         
    }

    private void devolver() {
        if(listadevol.getSelectedValue()==null)
            return;
        
        try{
            EmprestimoController devolucao = new EmprestimoController();
            devolucao.devolver(listadevol.getSelectedValue());
            preencherLista();
            limpar();
            matricula.requestFocus();
        } catch(SQLException e){
            Logger.getLogger("Erro Interface "+ e.getLocalizedMessage());
            
        }     

    }

    private void pegarPeriodo() {
        
        String di = i3.getText()+"-"+i2.getText()+"-"+i1.getText();
        String df = f3.getText()+f2.getText()+f1.getText();
        String dfLabel = f3.getText()+"-"+f2.getText()+"-"+f1.getText();
        
        int f = Integer.parseInt(df);
        f = f+1;
        df = Integer.toString(f);
        df = df.substring(0,4)+"-"+df.substring(4,6)+"-"+df.substring(6,8);
        
        if(di.length()!= 10 || df.length()!= 10) {
        } else{
            i1.setText("");i2.setText("");f1.setText("");f2.setText("");
            RelatorioMes rel = new RelatorioMes();
            rel.setVisible(true);
            rel.relatorioPeriodo(di, df, dfLabel);
            
        } 
        
    }
        
}