
package sistemachaves;

import relatorios.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class InterfaceChaves extends javax.swing.JFrame {
    Connection conn = null;
    private short totalChaves;
  

    public InterfaceChaves() {
        initComponents();
        conn = JavaConnect.connect();      
        
        //Descobrir número total de chaves
        String sql = "SELECT count(numchave) FROM chaves";

        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();          
            totalChaves = Short.parseShort(rs.getString(1));
            pst.close();
            rs.close();
            
        } catch (SQLException e) {
            System.out.println("Não conseguiu pegar número de chaves");
        }
        //Fim descobrir total de chaves
        
        try{
            conn.close();
            System.out.println("Conexão encerrada");
        } catch(SQLException e){
            System.out.println("Erro ao fechar a conexão");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        relatorios = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        telaemprestimo = new javax.swing.JPanel();
        pEmprestimo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chave = new javax.swing.JTextField();
        btemprestar = new javax.swing.JButton();
        nome = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        pDevolucao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadevol = new javax.swing.JList<>();
        btdevolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telainserir = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cadmatricula = new javax.swing.JTextField();
        cadnome = new javax.swing.JTextField();
        btcadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        telarelatorio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelRelatorio = new javax.swing.JLabel();
        relatorioEmprestimo = new javax.swing.JButton();
        relatorioMesAnterior = new javax.swing.JButton();
        relatorioMesAtual = new javax.swing.JButton();
        cbmeses = new javax.swing.JComboBox<>();
        relatorioMes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        i1 = new javax.swing.JFormattedTextField();
        i2 = new javax.swing.JFormattedTextField();
        i3 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        f1 = new javax.swing.JFormattedTextField();
        f2 = new javax.swing.JFormattedTextField();
        f3 = new javax.swing.JFormattedTextField();
        relatorioPeriodo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cabecalho = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        sistemachaves = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 1200));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(190, 210, 240));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(90, 100, 150));
        jTabbedPane1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        telaemprestimo.setBackground(new java.awt.Color(255, 255, 255));
        telaemprestimo.setMaximumSize(new java.awt.Dimension(1200, 1200));

        pEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        pEmprestimo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pEmprestimo.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Matrícula");

        matricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                matriculaFocusGained(evt);
            }
        });
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+1f));
        jLabel2.setText("Chave");

        chave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chaveFocusGained(evt);
            }
        });
        chave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaveActionPerformed(evt);
            }
        });

        btemprestar.setText("Emprestar");
        btemprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btemprestarActionPerformed(evt);
            }
        });

        nome.setFont(nome.getFont().deriveFont(nome.getFont().getSize()+2f));
        nome.setForeground(new java.awt.Color(90, 100, 150));
        nome.setName(""); // NOI18N

        data.setFont(data.getFont().deriveFont(data.getFont().getSize()+2f));
        data.setForeground(new java.awt.Color(90, 100, 150));

        javax.swing.GroupLayout pEmprestimoLayout = new javax.swing.GroupLayout(pEmprestimo);
        pEmprestimo.setLayout(pEmprestimoLayout);
        pEmprestimoLayout.setHorizontalGroup(
            pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEmprestimoLayout.createSequentialGroup()
                        .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEmprestimoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE))
                            .addGroup(pEmprestimoLayout.createSequentialGroup()
                                .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(29, 29, 29)))
                        .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btemprestar)
                            .addComponent(chave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        pEmprestimoLayout.setVerticalGroup(
            pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(chave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btemprestar)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDevolucao.setBackground(new java.awt.Color(255, 255, 255));
        pDevolucao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBorder(null);

        listadevol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listadevol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listadevol.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listadevol.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listadevolValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listadevol);

        javax.swing.GroupLayout pDevolucaoLayout = new javax.swing.GroupLayout(pDevolucao);
        pDevolucao.setLayout(pDevolucaoLayout);
        pDevolucaoLayout.setHorizontalGroup(
            pDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDevolucaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pDevolucaoLayout.setVerticalGroup(
            pDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );

        btdevolver.setText("Devolver");
        btdevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdevolverActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(90, 100, 150));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Empréstimo");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(90, 100, 150));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Devolução");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout telaemprestimoLayout = new javax.swing.GroupLayout(telaemprestimo);
        telaemprestimo.setLayout(telaemprestimoLayout);
        telaemprestimoLayout.setHorizontalGroup(
            telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaemprestimoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pDevolucao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        telaemprestimoLayout.setVerticalGroup(
            telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaemprestimoLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaemprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(telaemprestimoLayout.createSequentialGroup()
                        .addComponent(pDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btdevolver))
                    .addComponent(pEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        jLabel4.getAccessibleContext().setAccessibleName("Dev");

        jTabbedPane1.addTab("   Empréstimo e Devolução   ", telaemprestimo);

        telainserir.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(262, 120));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+1f));
        jLabel5.setText("Matrícula");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+1f));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nome");

        cadmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadmatriculaActionPerformed(evt);
            }
        });

        cadnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadnomeActionPerformed(evt);
            }
        });

        btcadastrar.setText("Cadastrar");
        btcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btcadastrar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadmatricula)
                            .addComponent(cadnome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cadmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cadnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btcadastrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(90, 100, 150));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cadastro de Usuário");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(83, 17));

        javax.swing.GroupLayout telainserirLayout = new javax.swing.GroupLayout(telainserir);
        telainserir.setLayout(telainserirLayout);
        telainserirLayout.setHorizontalGroup(
            telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telainserirLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        telainserirLayout.setVerticalGroup(
            telainserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telainserirLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   Cadastrar Usuário   ", telainserir);

        telarelatorio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelRelatorio.setBackground(new java.awt.Color(90, 100, 150));
        labelRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        labelRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelatorio.setText("Relatórios");
        labelRelatorio.setOpaque(true);

        relatorioEmprestimo.setText("Empréstimos ativos");
        relatorioEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioEmprestimoActionPerformed(evt);
            }
        });

        relatorioMesAnterior.setText("Mês anterior");
        relatorioMesAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioMesAnteriorActionPerformed(evt);
            }
        });

        relatorioMesAtual.setText("Mês atual");
        relatorioMesAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioMesAtualActionPerformed(evt);
            }
        });

        cbmeses.setFont(cbmeses.getFont().deriveFont(cbmeses.getFont().getStyle() | java.awt.Font.BOLD, cbmeses.getFont().getSize()+1));
        cbmeses.setForeground(new java.awt.Color(90, 100, 150));
        cbmeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cbmeses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbmesesKeyPressed(evt);
            }
        });

        relatorioMes.setText("Relatório por mês");
        relatorioMes.setMaximumSize(new java.awt.Dimension(93, 23));
        relatorioMes.setMinimumSize(new java.awt.Dimension(93, 23));
        relatorioMes.setPreferredSize(new java.awt.Dimension(93, 23));
        relatorioMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioMesActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()+1f));
        jLabel8.setText("Período inicial:");

        i1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd"))));
        i1.setFont(i1.getFont().deriveFont(i1.getFont().getSize()+1f));
        i1.setNextFocusableComponent(i2);
        i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1ActionPerformed(evt);
            }
        });

        i2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM"))));
        i2.setFont(i2.getFont().deriveFont(i2.getFont().getSize()+1f));
        i2.setNextFocusableComponent(i3);
        i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2ActionPerformed(evt);
            }
        });

        i3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        i3.setFont(i3.getFont().deriveFont(i3.getFont().getSize()+1f));
        i3.setNextFocusableComponent(f1);

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getSize()+1f));
        jLabel9.setText("Período final:");

        f1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd"))));
        f1.setFont(f1.getFont().deriveFont(f1.getFont().getSize()+1f));
        f1.setNextFocusableComponent(f2);
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        f2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM"))));
        f2.setFont(f2.getFont().deriveFont(f2.getFont().getSize()+1f));
        f2.setNextFocusableComponent(f3);
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        f3.setFont(f3.getFont().deriveFont(f3.getFont().getSize()+1f));

        relatorioPeriodo.setText("Relatório por período");
        relatorioPeriodo.setMaximumSize(new java.awt.Dimension(93, 23));
        relatorioPeriodo.setMinimumSize(new java.awt.Dimension(93, 23));
        relatorioPeriodo.setPreferredSize(new java.awt.Dimension(93, 23));
        relatorioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioPeriodoActionPerformed(evt);
            }
        });

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getSize()+1f));
        jLabel10.setText("/");

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getSize()+1f));
        jLabel11.setText("/");

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getSize()+1f));
        jLabel12.setText("/");

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getSize()+1f));
        jLabel13.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(relatorioPeriodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relatorioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatorioMesAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(relatorioMesAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(relatorioEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbmeses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(relatorioMes, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(relatorioEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmeses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatorioMesAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relatorioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(relatorioMesAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telarelatorioLayout = new javax.swing.GroupLayout(telarelatorio);
        telarelatorio.setLayout(telarelatorioLayout);
        telarelatorioLayout.setHorizontalGroup(
            telarelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telarelatorioLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        telarelatorioLayout.setVerticalGroup(
            telarelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telarelatorioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   Relatórios   ", telarelatorio);

        cabecalho.setBackground(new java.awt.Color(255, 255, 255));

        logo.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        logo.setForeground(new java.awt.Color(153, 0, 0));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N

        sistemachaves.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        sistemachaves.setForeground(new java.awt.Color(153, 0, 0));
        sistemachaves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sistemachaves.setText("Sistema de chaves");

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sistemachaves)
                .addGap(17, 17, 17))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sistemachaves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("  Empréstimo e Devolução  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        conn = JavaConnect.connect();
        preencherLista();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        try{
            conn.close();
            System.out.println("Conexão encerrada");
        } catch(SQLException e){
            System.out.println("Erro ao fechar a conexão");
        }
    }//GEN-LAST:event_formWindowLostFocus

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        if(jTabbedPane1.getSelectedIndex() == 0)
        matricula.requestFocus();
        else
        cadmatricula.requestFocus();

        LocalDateTime dia = LocalDateTime.now();
        i3.setText(Integer.toString(dia.getYear()));
        f3.setText(Integer.toString(dia.getYear()));
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void relatorioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioPeriodoActionPerformed
        pegarPeriodo();
    }//GEN-LAST:event_relatorioPeriodoActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        relatorioPeriodo.requestFocus();
    }//GEN-LAST:event_f2ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        f2.requestFocus();
    }//GEN-LAST:event_f1ActionPerformed

    private void i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2ActionPerformed
        f1.requestFocus();
    }//GEN-LAST:event_i2ActionPerformed

    private void i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1ActionPerformed
        i2.requestFocus();
    }//GEN-LAST:event_i1ActionPerformed

    private void relatorioMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioMesActionPerformed
        RelatorioMes rel = new RelatorioMes();
        rel.setVisible(true);
        String nomemes = (String)cbmeses.getSelectedItem();
        int nummes = (cbmeses.getSelectedIndex())+1;
        rel.relatorioMes(conn, nummes, nomemes);
    }//GEN-LAST:event_relatorioMesActionPerformed

    private void cbmesesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbmesesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        relatorioMes.requestFocus();
    }//GEN-LAST:event_cbmesesKeyPressed

    private void relatorioMesAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioMesAtualActionPerformed
        RelatorioMes rel = new RelatorioMes();
        rel.setVisible(true);
        rel.relatorioMesAtual(conn);
    }//GEN-LAST:event_relatorioMesAtualActionPerformed

    private void relatorioMesAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioMesAnteriorActionPerformed
        RelatorioMes rel = new RelatorioMes();
        rel.setVisible(true);
        rel.relatorioMesAnterior(conn);
    }//GEN-LAST:event_relatorioMesAnteriorActionPerformed

    private void relatorioEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioEmprestimoActionPerformed
        RelatorioEmpAtivo rel = new RelatorioEmpAtivo();
        rel.setVisible(true);
        rel.relatorioEmprestimoAtivo(conn);
    }//GEN-LAST:event_relatorioEmprestimoActionPerformed

    private void btcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btcadastrarActionPerformed

    private void cadnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadnomeActionPerformed
        cadastrar();
    }//GEN-LAST:event_cadnomeActionPerformed

    private void cadmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadmatriculaActionPerformed
        cadnome.requestFocus();
    }//GEN-LAST:event_cadmatriculaActionPerformed

    private void btdevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdevolverActionPerformed
        devolver();
    }//GEN-LAST:event_btdevolverActionPerformed

    private void listadevolValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listadevolValueChanged
        btdevolver.requestFocus();
    }//GEN-LAST:event_listadevolValueChanged

    private void btemprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btemprestarActionPerformed
        empAtivo();
    }//GEN-LAST:event_btemprestarActionPerformed

    private void chaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaveActionPerformed
        empAtivo();
    }//GEN-LAST:event_chaveActionPerformed

    private void chaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chaveFocusGained
        exibirEmp();
    }//GEN-LAST:event_chaveFocusGained

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        chave.requestFocus();
    }//GEN-LAST:event_matriculaActionPerformed

    private void matriculaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_matriculaFocusGained
        limpar();
    }//GEN-LAST:event_matriculaFocusGained


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceChaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceChaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastrar;
    private javax.swing.JButton btdevolver;
    private javax.swing.JButton btemprestar;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JTextField cadmatricula;
    private javax.swing.JTextField cadnome;
    private javax.swing.JComboBox<String> cbmeses;
    private javax.swing.JTextField chave;
    private javax.swing.JLabel data;
    private javax.swing.JFormattedTextField f1;
    private javax.swing.JFormattedTextField f2;
    private javax.swing.JFormattedTextField f3;
    private javax.swing.JFormattedTextField i1;
    private javax.swing.JFormattedTextField i2;
    private javax.swing.JFormattedTextField i3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelRelatorio;
    private javax.swing.JList<String> listadevol;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField matricula;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel pDevolucao;
    private javax.swing.JPanel pEmprestimo;
    private javax.swing.JButton relatorioEmprestimo;
    private javax.swing.JButton relatorioMes;
    private javax.swing.JButton relatorioMesAnterior;
    private javax.swing.JButton relatorioMesAtual;
    private javax.swing.JButton relatorioPeriodo;
    private javax.swing.ButtonGroup relatorios;
    private javax.swing.JLabel sistemachaves;
    private javax.swing.JPanel telaemprestimo;
    private javax.swing.JPanel telainserir;
    private javax.swing.JPanel telarelatorio;
    // End of variables declaration//GEN-END:variables

    
    private void limpar(){
        matricula.setText("");
        chave.setText("");
        nome.setText("");
        data.setText("");
        cadmatricula.setText("");
        cadnome.setText("");
        listadevol.clearSelection();
    }
       
    private void cadastrar() {
        
        if(cadmatricula.getText().isEmpty() || cadnome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falha no cadastro. Campos não preenchidos");
            
        } else{
            System.out.println(cadmatricula.getText()+ cadnome.getText());
        
            String sql = "INSERT INTO alunos VALUES(?,?)";

            try {
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, cadmatricula.getText());
                pst.setString(2, cadnome.getText());
                pst.executeUpdate();
                pst.close();
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso.");                             

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Falha no cadastro. Já existe usuário cadastrado com essa matrícula.");


            } finally{
                String aux = cadmatricula.getText();
                jTabbedPane1.setSelectedIndex(0);                                   
                limpar();
                //copy(aux);
                matricula.setText(aux);
                chave.requestFocus();

            }
        }
    
    }
    
    private void copy(String aux){
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(aux);
        clipboard.setContents(selection, null);
    }
    
    private boolean chaveValida(){
        
        if(nome.getText().isEmpty())
            return false;
        
        if("".equals(chave.getText()))
            return false;
            
        int i = Integer.parseInt(chave.getText());
        
        if (i>0 && i<=totalChaves)
            return true;
        else{
            JOptionPane.showMessageDialog(null, "Número de chave inválido. A chave deve ser até "+ totalChaves);
            chave.setText("");
            return false;
        }
    
    }
    
    private void empAtivo(){
        boolean chV = chaveValida();
        if (!chV){
            return;           
        }
        
                  
        String sql = "SELECT emp_aluno, emp_chave FROM emprestimos WHERE (emp_aluno = ? OR emp_chave = ?) AND datadev IS NULL";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, matricula.getText());
            pst.setString(2, chave.getText());              
            ResultSet rs = pst.executeQuery();
                      
            if(!rs.isBeforeFirst()){//se não achar emprestimo ativo com essa matricula e chave, fazer emprestimo
                pst.close();
                rs.close();
                emprestar();
            }else if (rs.getString(1).equals(matricula.getText())){
                pst.close();
                rs.close();
                JOptionPane.showMessageDialog(null, "O usuário já possui empréstimo ativo");
                limpar();
                matricula.requestFocus();
            }
            else if (rs.getString(2).equals(chave.getText())){
                pst.close();
                rs.close();
                JOptionPane.showMessageDialog(null, "Essa chave já está emprestada");
                chave.setText("");
                chave.requestFocus();
            }
                                       
        } catch (SQLException e){
            System.out.println("Erro ao verificar os empréstimos ativos");
           
        }       
    }
    

    private void emprestar() {       
        String sql = "INSERT INTO emprestimos (emp_aluno, emp_chave) VALUES(?,?)";
        nome.setForeground(Color.black);
                         
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, matricula.getText());
            pst.setString(2, chave.getText());
            pst.executeUpdate();           
            pst.close();
            preencherLista();
            
            limpar();
            matricula.requestFocus();  
                        
        } catch (SQLException e) {
            System.out.println("Empréstimo não foi efetuado pois o usuário não está cadastrado");
            String aux = matricula.getText();
            limpar();
            jTabbedPane1.setSelectedIndex(1);
            cadmatricula.setText(aux);
            
        }      
    }

    private void exibirEmp() {
        if ("".equals(matricula.getText()))
            return;
        
        String sql = "SELECT nome FROM alunos WHERE matricula = ?";
        nome.setForeground(new Color(90,100,150));
        btemprestar.setEnabled(true);
               
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, matricula.getText());           
            ResultSet rs = pst.executeQuery();

            nome.setText("Nome: "+ rs.getString("nome")); // Poderia ser também getString(1), para dizer que é o primeiro campo da tabela
            LocalDateTime dia = LocalDateTime.now();
            DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy - HH:mm");
            data.setText("Data de empréstimo: " + dia.format(formatador));
            pst.close();
            rs.close();
        
        } catch (SQLException e){
            nome.setForeground(new Color(153,0,0));
            nome.setText("Usuário não cadastrado.");
            cadmatricula.setText(matricula.getText());
            data.setText("");
            btemprestar.setEnabled(false);
                       
        }
                     
    }

    private void preencherLista() {        
        DefaultListModel model = new DefaultListModel();
        listadevol.setModel(model);
        
        String sql = "SELECT emp_chave FROM emprestimos WHERE datadev IS NULL ORDER BY emp_chave";
        
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                model.addElement(rs.getString(1));                
            }
            pst.close();
            rs.close();
                       
        }catch (SQLException e){
            System.out.println("Não há empréstimos ativos");
            
        }               
    }

    private void devolver() {
        if(listadevol.getSelectedValue()==null)
            return;
                
        String sql = "UPDATE emprestimos SET datadev=(datetime('now','-3 hour')) WHERE emp_chave = ? AND datadev IS NULL";
               
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, listadevol.getSelectedValue());
            pst.executeUpdate();      
            pst.close();
            preencherLista();   
        
        }catch (SQLException e){
            System.out.println("Nenhuma chave selecionada");
        }finally{
            matricula.requestFocus();
        }
        
        
    }

    private void pegarPeriodo() {
        
        String di = i3.getText()+"-"+i2.getText()+"-"+i1.getText();
        String df = f3.getText()+f2.getText()+f1.getText();
        
        int f = Integer.parseInt(df);
        f = f+1;
        df = Integer.toString(f);
        df = df.substring(0,4)+"-"+df.substring(4,6)+"-"+df.substring(6,8);
        
        if(di.length()!= 10 || df.length()!= 10) {
        } else{
            i1.setText("");i2.setText("");f1.setText("");f2.setText("");
            RelatorioMes rel = new RelatorioMes();
            rel.setVisible(true);
            rel.relatorioPeriodo(conn, di, df);
            
        }          
        
    }
    
    
}